language: node_js
node_js:
  - '10'

cache:
  yarn: true
  directories:
    - 'node_modules'

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - mkdir -p ~/.local/bin
  - export PATH="$HOME/.local/bin:$HOME/.yarn/bin:$PATH"
  - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
branches:
  only:
    - master

before_deploy:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null

deploy:
  - provider: script
    script: 'yarn lerna:publish --yes'
    skip_cleanup: true
    on:
      branch: master
